_extends: peft_uni2_scale64_fold0.yaml
run_name: s02a_uni2_scale64_hardw_fold0

class_weighting:
  mode: manual
  normalize_mean: true
  weights:
    Class_0: 1.00
    Class_1: 1.00
    Class_2: 1.00
    Class_3: 1.25
    Class_4: 1.10

experiments:
  - name: rslora_qkv_proj_r16_no_ema_scale64_hardw
    backbone_keys: [uni2_h]
    mode: lora
    batch_size: 16
    head_lr: 0.0005
    adapter_lr: 0.00005
    ema_decay: 0.0
    target_policy: attention_qkv_proj
    lora:
      r: 16
      alpha: 32
      dropout: 0.05
      bias: none
      modules_to_save: [classifier]
      use_rslora: true
