"""Dataset and augmentation utilities for supervised image training."""

from __future__ import annotations

import csv
import random
from pathlib import Path
from typing import Any

from PIL import Image
from torch.utils.data import Dataset
from torchvision import transforms

from ml_final.utils.config import resolve_project_path


class ManifestImageDataset(Dataset):
    """Dataset backed by an audit CSV manifest."""

    def __init__(
        self,
        rows: list[dict[str, str]],
        *,
        label_to_idx: dict[str, int],
        transform,
    ) -> None:
        self.rows = rows
        self.label_to_idx = label_to_idx
        self.transform = transform

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, index: int):
        row = self.rows[index]
        image_path = resolve_project_path(row["abs_path"])
        if image_path is None:
            raise ValueError("manifest row path cannot be empty")
        image = Image.open(image_path).convert("RGB")
        if self.transform is not None:
            image = self.transform(image)
        label = self.label_to_idx[row["label"]]
        return image, label, row["filename"]


class MultiTransformManifestDataset(Dataset):
    """Labeled manifest dataset that returns one tensor per model branch."""

    def __init__(
        self,
        rows: list[dict[str, str]],
        *,
        label_to_idx: dict[str, int],
        transforms_by_key: dict[str, Any],
    ) -> None:
        self.rows = rows
        self.label_to_idx = label_to_idx
        self.transforms_by_key = dict(transforms_by_key)

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, index: int):
        row = self.rows[index]
        image_path = resolve_project_path(row["abs_path"])
        if image_path is None:
            raise ValueError("manifest row path cannot be empty")
        image = Image.open(image_path).convert("RGB")
        images = {
            key: transform(image.copy()) if transform is not None else image.copy()
            for key, transform in self.transforms_by_key.items()
        }
        label = self.label_to_idx[row["label"]]
        return images, label, row["filename"]


class MultiTransformUnlabeledDataset(Dataset):
    """Unlabeled manifest dataset that returns one tensor per model branch."""

    def __init__(self, rows: list[dict[str, str]], *, transforms_by_key: dict[str, Any]) -> None:
        self.rows = rows
        self.transforms_by_key = dict(transforms_by_key)

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, index: int):
        row = self.rows[index]
        image_path = resolve_project_path(row["abs_path"])
        if image_path is None:
            raise ValueError("image path cannot be empty")
        image = Image.open(image_path).convert("RGB")
        images = {
            key: transform(image.copy()) if transform is not None else image.copy()
            for key, transform in self.transforms_by_key.items()
        }
        return images, row["filename"]


def read_manifest(path: str | Path) -> list[dict[str, str]]:
    """Read a CSV manifest generated by dataset audit."""

    with Path(path).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def build_label_mapping(rows: list[dict[str, str]]) -> tuple[list[str], dict[str, int]]:
    """Return sorted class names and label-to-index map."""

    class_names = sorted({row["label"] for row in rows})
    return class_names, {label: idx for idx, label in enumerate(class_names)}


def build_transform(config: dict[str, Any], *, train: bool, input_size: int):
    """Build torchvision transform from a conservative augmentation config."""

    aug = dict(config or {})
    mean = aug.get("mean", [0.485, 0.456, 0.406])
    std = aug.get("std", [0.229, 0.224, 0.225])
    interpolation = str(aug.get("interpolation", "bicubic")).lower()
    interpolation_mode = (
        transforms.InterpolationMode.BILINEAR
        if interpolation in {"bilinear", "linear"}
        else transforms.InterpolationMode.BICUBIC
    )
    crop_pct = float(aug.get("crop_pct", 1.0))
    ops = []
    scale_to = optional_positive_int(aug.get("scale_to"))
    random_resized_crop = aug.get("random_resized_crop") if train else None
    if scale_to is not None:
        if random_resized_crop:
            raise ValueError("scale_to cannot be combined with random_resized_crop")
        ops.append(
            CenterScalePad(
                input_size=input_size,
                scale_to=scale_to,
                fill=resolve_scale_pad_fill_rgb(aug),
                interpolation=interpolation_mode,
            )
        )
    elif random_resized_crop:
        scale = random_resized_crop.get("scale", [0.8, 1.0])
        ratio = random_resized_crop.get("ratio", [0.9, 1.1])
        ops.append(
            transforms.RandomResizedCrop(
                input_size,
                scale=(float(scale[0]), float(scale[1])),
                ratio=(float(ratio[0]), float(ratio[1])),
                interpolation=interpolation_mode,
            )
        )
    elif train or crop_pct >= 1.0:
        ops.append(transforms.Resize((input_size, input_size), interpolation=interpolation_mode))
    else:
        resize_size = max(input_size, int(round(input_size / max(crop_pct, 1e-6))))
        ops.extend(
            [
                transforms.Resize(resize_size, interpolation=interpolation_mode),
                transforms.CenterCrop(input_size),
            ]
        )
    if train:
        if float(aug.get("hflip_prob", 0.0)) > 0:
            ops.append(transforms.RandomHorizontalFlip(p=float(aug["hflip_prob"])))
        if float(aug.get("vflip_prob", 0.0)) > 0:
            ops.append(transforms.RandomVerticalFlip(p=float(aug["vflip_prob"])))
        if float(aug.get("rot90_prob", 0.0)) > 0:
            ops.append(RandomQuarterTurn(p=float(aug["rot90_prob"])))
        translate = float(aug.get("translate", 0.0))
        if translate > 0:
            ops.append(
                transforms.RandomAffine(
                    degrees=0,
                    translate=(translate, translate),
                    interpolation=transforms.InterpolationMode.BICUBIC,
                    fill=resolve_fill_rgb(aug, mean),
                )
            )
        jitter = aug.get("color_jitter")
        if jitter:
            ops.append(
                transforms.ColorJitter(
                    brightness=float(jitter.get("brightness", 0.0)),
                    contrast=float(jitter.get("contrast", 0.0)),
                    saturation=float(jitter.get("saturation", 0.0)),
                    hue=float(jitter.get("hue", 0.0)),
                )
            )
    ops.extend([transforms.ToTensor(), transforms.Normalize(mean=mean, std=std)])
    return transforms.Compose(ops)


def build_official_preprocess_transform(config: dict[str, Any], *, train: bool, official_preprocess):
    """Apply project PIL augmentations before an official model preprocess."""

    if official_preprocess is None:
        raise ValueError("official_preprocess is required")
    pil_aug = build_pil_augmentation(config, train=train)
    if pil_aug is None:
        return official_preprocess
    return transforms.Compose([pil_aug, official_preprocess])


def build_pil_augmentation(config: dict[str, Any], *, train: bool):
    """Build only PIL-domain augmentations, leaving resize/tensor/normalize to the caller."""

    aug = dict(config or {})
    mean = aug.get("mean", [0.485, 0.456, 0.406])
    interpolation = str(aug.get("interpolation", "bicubic")).lower()
    interpolation_mode = (
        transforms.InterpolationMode.BILINEAR
        if interpolation in {"bilinear", "linear"}
        else transforms.InterpolationMode.BICUBIC
    )
    ops = []
    input_size = int(aug.get("input_size", 224))
    scale_to = optional_positive_int(aug.get("scale_to"))
    random_resized_crop = aug.get("random_resized_crop") if train else None
    if scale_to is not None:
        if random_resized_crop:
            raise ValueError("scale_to cannot be combined with random_resized_crop")
        ops.append(
            CenterScalePad(
                input_size=input_size,
                scale_to=scale_to,
                fill=resolve_scale_pad_fill_rgb(aug),
                interpolation=interpolation_mode,
            )
        )
    if random_resized_crop:
        scale = random_resized_crop.get("scale", [0.8, 1.0])
        ratio = random_resized_crop.get("ratio", [0.9, 1.1])
        ops.append(
            transforms.RandomResizedCrop(
                int(random_resized_crop.get("size", aug.get("input_size", 224))),
                scale=(float(scale[0]), float(scale[1])),
                ratio=(float(ratio[0]), float(ratio[1])),
                interpolation=interpolation_mode,
            )
        )
    if float(aug.get("hflip_prob", 0.0)) > 0:
        ops.append(transforms.RandomHorizontalFlip(p=float(aug["hflip_prob"])))
    if float(aug.get("vflip_prob", 0.0)) > 0:
        ops.append(transforms.RandomVerticalFlip(p=float(aug["vflip_prob"])))
    if float(aug.get("rot90_prob", 0.0)) > 0:
        ops.append(RandomQuarterTurn(p=float(aug["rot90_prob"])))
    translate = float(aug.get("translate", 0.0))
    if translate > 0:
        ops.append(
            transforms.RandomAffine(
                degrees=0,
                translate=(translate, translate),
                interpolation=interpolation_mode,
                fill=resolve_fill_rgb(aug, mean),
            )
        )
    jitter = aug.get("color_jitter")
    if jitter:
        ops.append(
            transforms.ColorJitter(
                brightness=float(jitter.get("brightness", 0.0)),
                contrast=float(jitter.get("contrast", 0.0)),
                saturation=float(jitter.get("saturation", 0.0)),
                hue=float(jitter.get("hue", 0.0)),
            )
        )
    if not ops:
        return None
    return transforms.Compose(ops)


def resolve_fill_rgb(aug: dict[str, Any], mean: list[float]) -> tuple[int, int, int]:
    """Return a natural RGB fill color for spatial transforms.

    Black padding is a strong artifact for small H&E cell crops, where a 5%
    translation can affect a large fraction of the 32x32 source image.
    """

    fill = aug.get("fill_rgb", aug.get("fill", "mean"))
    if isinstance(fill, str):
        if fill != "mean":
            raise ValueError(f"unsupported fill value: {fill}")
        values = [int(round(float(channel) * 255.0)) for channel in mean]
    else:
        values = [int(round(float(channel))) for channel in fill]
    if len(values) != 3:
        raise ValueError("fill_rgb must contain exactly three RGB values")
    return tuple(max(0, min(255, value)) for value in values)


def resolve_scale_pad_fill_rgb(aug: dict[str, Any]) -> tuple[int, int, int]:
    """Resolve the RGB canvas fill for opt-in cell scale-pad preprocessing."""

    fill = aug.get("scale_pad_fill_rgb", [255, 255, 255])
    if isinstance(fill, str):
        if fill != "white":
            raise ValueError(f"unsupported scale_pad_fill_rgb value: {fill}")
        values = [255, 255, 255]
    else:
        values = [int(round(float(channel))) for channel in fill]
    if len(values) != 3:
        raise ValueError("scale_pad_fill_rgb must contain exactly three RGB values")
    return tuple(max(0, min(255, value)) for value in values)


def optional_positive_int(value: Any) -> int | None:
    """Return a positive integer if configured, otherwise None."""

    if value is None:
        return None
    result = int(value)
    if result <= 0:
        raise ValueError(f"expected a positive integer, got {value!r}")
    return result


class CenterScalePad:
    """Resize a cell crop to a smaller centered view on a fixed square canvas."""

    def __init__(
        self,
        *,
        input_size: int,
        scale_to: int,
        fill: tuple[int, int, int],
        interpolation: transforms.InterpolationMode,
    ) -> None:
        if scale_to > input_size:
            raise ValueError(f"scale_to must be <= input_size, got scale_to={scale_to}, input_size={input_size}")
        self.input_size = int(input_size)
        self.scale_to = int(scale_to)
        self.fill = fill
        self.interpolation = interpolation

    def __call__(self, image: Image.Image) -> Image.Image:
        resized = transforms.functional.resize(
            image,
            [self.scale_to, self.scale_to],
            interpolation=self.interpolation,
        )
        canvas = Image.new("RGB", (self.input_size, self.input_size), color=self.fill)
        offset = ((self.input_size - self.scale_to) // 2, (self.input_size - self.scale_to) // 2)
        canvas.paste(resized, offset)
        return canvas


class RandomQuarterTurn:
    """Random 90-degree rotation without arbitrary interpolation angles."""

    def __init__(self, p: float = 0.5) -> None:
        self.p = p

    def __call__(self, image: Image.Image) -> Image.Image:
        if random.random() >= self.p:
            return image
        turns = random.choice([1, 2, 3])
        return image.rotate(90 * turns, expand=True)
