_extends: pseudo_lora_uni2_scale64_hardw_lam0015_iter2_soft150.yaml
run_name: s03_uni2_scale64_hardw_pseudo_lam0015_iter2_soft150_pcw_c4up
lambda_pseudo: 0.0015
skip_completed: true

pseudo_class_weight:
  Class_0: 1.0
  Class_1: 1.0
  Class_2: 1.0
  Class_3: 1.0
  Class_4: 1.15
