run_name: s01_fusion_variants
fusion_id: single_uni_conch
output_dir: artifacts/features/scheme_01/s01_fusion_variants
sources:
  - name: uni2_h
    path: artifacts/features/scheme_01/s01_single/uni2_h/uni2_h_timm_tta-none_5eb18eca11.npz
    weight: 1.0
  - name: conch
    path: artifacts/features/scheme_01/s01_single/conch/conch_conch_tta-none_effa33cf57.npz
    weight: 1.0
